<?php

	/**
	* @file
	*Provides functions and callbakc for managing a blobal word list
	*for example managing blacklisted words.
	*/


/*
* Implements hook_menu().
*/
function wordlist_menu() {
	$items['admin/config/content/wordlist'] = array(
		'title' => 'Word list',
		'description' => 'Manage the list of globally available words on your site.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('wordlist_page'),
		'access callback' => 'user_access',
		'access arguments' =>  array('administer_site_configuration'),
		'menu_name' => 'management',
	);

	return $items;
}

/**
 * Builds the form for configuring Word list.
 */

function wordlist_page() {

		$form['wordlist_words'] = array(
			'#type' => 'textarea',
			'#title' => t('Words to include in the list'),
			'#description' => t('The words included in this list will be available to Rules and other modules making use of the global "site" entity.'),
			'#default_value' => implode("\r\n", variable_get('wordlist_words', array())),
		);
		$form['submit'] = array(
			'#type' => 'submit',
			'#value' => t('Save')
		);

	return $form;
}


/**
 * Submit function for the Word list configurations page
 */
function wordlist_page_submit($form, $form_state) {
	// Break up the list of words according to line breaks.
	$words = explode("\r\n", $form_state['input']['wordlist_words']);
	
	wordlist_save_list($words);
	drupal_set_message(t('The words have been saved!'));
}


/**
 * Stores the globally accessible Word list words.
 * @param $words
 * An array containing the words that should be stored.
 */
function wordlist_save_list(array $words) {
	// Check if the list of words contain any empty strings, and remove them.
	$removed = 0;
	foreach ($words as $key => $word) {
		if (drupal_strlen($word) == 0) {
			unset($words[$key]);
			$removed++;
		}
	}

	// If any strings were removed, notify the user.
	if ($removed > 0) {
		drupal_set_message(t(
			'Removed @number empty words.', 
			array('@number' => $removed)));
	}

	// Store the words in the variables table.
	variable_set('wordlist_words', $words);
}





